version: '3'
services:
   db:
     image: mysql:5.6.40
     environment:
        - MYSQL_ROOT_PASSWORD=secret 
        - MYSQL_ROOT_HOST=%
     ports:
        - "33333:3306"
   web:
     build: .
     command: bash b.sh
     volumes:
        - .:/myapp
     ports:
        - "5555:3333"
     depends_on:
        - db

   solr:
     image: solr
     volumes:
        - data:/opt/solr/server/solr/mycores 
     entrypoint:
        - docker-entrypoint.sh
        - solr-precreate
        - mycore
     ports:
        - "8999:8983"
     depends_on:
        - web
volumes:
   data:
