production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/mycore
    # read_timeout: 2
    # open_timeout: 0.5
    # docker stop start test? modified?

development:
  solr:
    #hostname: localhost
    hostname: solr
    #port: 8983
    port: 8983
    log_level: INFO
    path: /solr/mycore

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    
